# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
      - master
  tags:
    include:
    - v*

pool:
  vmImage: 'macOS-10.14'

steps:
- checkout: self
  submodules: true
- task: Xcode@5
  inputs:
    actions: 'build'
    args: '-target CreateDiskImage'
    sdk: 'macosx10.14'
    configuration: 'Release'
    xcWorkspacePath: 
    xcodeVersion: '10' # Options: 8, 9, 10, default, specifyPath
- task: CopyFiles@2
  inputs:
    contents: 'build/Release/PacketPeeper*.dmg'
    targetFolder: $(Build.ArtifactStagingDirectory)
#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHubServiceConnection'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: '^\d{4}-\d{2}-\d{2}$'
    releaseNotesSource: 'inline'
    addChangeLog: false
    #assets: $(Build.ArtifactStagingDirectory)/*.dmg
    isDraft: true
