name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Build
        run: xcodebuild -target All -configuration Release
