
name: Xcode-Release

on:
  release:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: init submodules
        run: git submodule update --init --recursive

      - name: Build
        run: xcodebuild -target CreateDiskImage -configuration Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/PacketPeeper_*.dmg
